CREATE TABLE cliente
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo_cliente  VARCHAR(255),
    cnpj          VARCHAR(14),
    razao_social  VARCHAR(50),
    mcc           VARCHAR(4)                              NOT NULL,
    cpf           VARCHAR(11),
    nome          VARCHAR(50),
    email         VARCHAR(255),
    cpf_contato   VARCHAR(11),
    nome_contato  VARCHAR(50),
    email_contato VARCHAR(255),
    CONSTRAINT pk_cliente PRIMARY KEY (id)
);